#! /usr/bin/env bash

LOCALAPPDATA_NIX=$(echo "$LOCALAPPDATA" | sed 's/\\/\//g')
rstudio="$LOCALAPPDATA_NIX"/RStudio/bin/rstudio
if [ -f .Rversion ]; then
  APPDATA_NIX=$(echo "$APPDATA" | sed 's/\\/\//g')
  R_PATH="$LOCALAPPDATA_NIX"/R
  VER=$(/bin/cat .Rversion)
  VERS=$(/bin/ls "$R_PATH" | /usr/bin/grep R-"$VER")
  if [[ "$VERS" == "" ]]; then
    echo "R version" "$VER" "not installed" && exit
  else
    desktopini="$APPDATA_NIX"/RStudio/desktop.ini
    VER_PATH=$(echo $VERS | /usr/bin/awk '{print $NF}')
    R_HOME="$R_PATH"/"$VER_PATH"/bin/x64
    OLD=$(/usr/bin/cat "$desktopini" | grep '^RBinDir.*$')
    powershell -Command "(get-content -Path $desktopini) -replace '$OLD', 'RBinDir=$R_HOME' | Set-Content -Path $desktopini"
  fi
fi
("$rstudio" &)
if [ ! -z "$OLD" ]; then
  sleep 1
  powershell -Command "(get-content -Path $desktopini) -replace 'RBinDir=$R_HOME', '$OLD' | Set-Content -Path $desktopini"
fi
